# Site settings
title: RoboticaClup
description: >
  Dit is de Metis RoboticaClup, hier zijn wij dag en nacht bezig met robots
  maken.
baseurl: "/RoboticaClup"
url: "http://metismontessorilyceum.github.io"

# Build settings
markdown: kramdown

host: 0.0.0.0

# Prose settings
prose:
  media: 'assets'
  rooturl: "_posts"
  metadata:
    _posts/blog:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          placeholder: "title"
      - name: "image"
        field:
          element: "text"
          placeholder: "big image, eg. noah-robot.jpg"
    _posts/team:
      - name: "category"
        field:
          element: "hidden"
          value: "team"
      - name: "title"
        field:
          element: "text"
          placeholder: "name"
      - name: "image"
        field:
          element: "text"
          placeholder: "big image, eg. noah-robot.jpg"
